SELECT fs.no_urut,
       fs.ref,
       fs.tgl_ref,
       dd.day,
       dd.month,
       dd.year,
       dd.week,
       dd.quarter,
       fs.no_ref,
       fs.no_dok_ref,
       fs.kode_cust,
       dc.nama_cust,
       dc.alamat_cust,
       dc.kode_kota,
       dc.nama_kota,
       fs.kode_sales,
       dsp.nama_sales,
       fs.pajak,
       fs.kategori_pajak,
       fs.kode_barang,
       dp.nama_jns_brg,
       fs.qty,
       fs.sat,
       fs.qty_std,
       dp.sat_std,
       fs.harga_plus,
       fs.harga_sbl_plus,
       fs.harga_unit_mu,
       fs.total_mu,
       fs.disc_1_pct,
       fs.disc_1_mu,
       fs.disc_2_pct,
       fs.disc_2_mu,
       fs.disc_3_pct,
       fs.disc_3_mu,
       fs.disc_4_mu,
       fs.disc_5_pct,
       fs.disc_5_mu,
       fs.disc_6_mu,
       fs.subtot_disc_mu,
       fs.subtot_mu,
       fs.hrg_unit_rill_mu,
       fs.total_rill_mu,
       fs.subtot_disc_rill_mu,
       fs.subtot_rill_mu,
       fs.disc_akh_mu,
       fs.subtot_net_mu,
       fs.pjk_mu,
       fs.subtot_net_pjk_mu
FROM fact_sales fs
JOIN dim_date dd ON fs.tgl_ref = dd.tgl_ref
JOIN dim_cust dc ON fs.kode_cust = dc.kode_cust
JOIN dim_salesperson dsp ON fs.kode_sales = dsp.kode_sales
JOIN dim_product dp ON fs.kode_barang = dp.kode_barang
AND fs.sat = dp.sat
ORDER BY fs.no_urut ASC